name: Gen Changelog
on:
  push:
    branches:
      - master

jobs:
  generate_changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1

      - name: Running standard changelog
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npx conventional-changelog-cli -p angular -o CHANGELOG_PSR.md -r 0
          npx conventional-changelog-cli -p angular -o CHANGELOG_PSR_2.md
          git add CHANGELOG_PSR.md CHANGELOG_PSR_2.md
          git commit -m "chore: autogeração do changelog"
          git push