name: Verificas as issues
on:
  issues:
    types: [opened, edited]

jobs:
  build:
    name: Verificando a issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: ./check-issues
