name: Generate Doc
on: 
  push:
    branches:
      - documentation

jobs:
  generate_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        run: npm install
        run: npm run docs:build
        run: git push origin documentation:gh-pages
