name: Generate Doc
on: 
  push:
    branches:
      - documentation

jobs:
  generate_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            ssh-key: ${{ secrets.SSH_KEY }}

      - name: Deploy Doc
        run: |
            mkdir -p ./src/.vuepress/dist/file.txt
            echo "PSR Test" > ./src/.vuepress/dist/file.txt
            git init
            git remote add origin https://github.com/${{ github.repository }}.git
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add -A
            git commit -m "chore: Deploy site"
            git push -f git@github.com:${{ github.repository }}.git master:gh-pages