name: Generate Doc
on: 
  push:
    branches:
      - documentation

jobs:
  generate_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            ref: gh-pages
        
      - name: Deploy
        uses: ./.github/actions/doc-deploy
        env:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BRANCH_FROM: documentation
            BRANCH_TO: gh-pages
            BUILD_SCRIPT: yarn && yarn build
            BUILD_DIR: src/.vuepress/dist/