name: Generate Doc
on: 
  push:
    branches:
      - documentation

jobs:
  generate_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup NodeJS
        uses: actions/setup-node@v1
      
      - name: Install Dependencies
        run: npm install

      - name: Generate Doc
        run: npm run build

      - name: Deploy Doc
        run: |
            git checkout gh-pages
            git checkout documentation -- ./src/.vuepress/dist
            git add -A
            git commit -m "chore: Deploy"
            git push