name: A workflow for my Hello World file
on: push

jobs:
    build:
        name: Hello world action
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
              
            - name: Action Dockerfile
              uses: ./action-a
              with:
                  MY_NAME: "Valdeir Psr"

            - name: Check file
              run: |
                  wget -O composer-setup.php https://getcomposer.org/installer
                  php composer-setup.php --install-dir=/
                  composer --version
                  
            - name: PHPUnit Install
              run: composer require phpunit/phpunit
              
            - name: PHPUnit Version
              run: php vendor/bin/phpunit --version
