name: 'Test PR Sync'
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: 'Test PR Sync'
    runs-on: ubuntu-latest
    steps:
      - name: 'Print'
        run: "echo Event Name ${{ GITHUB_EVENT_NAME }}"
