name: Test PR
on: 
    push:
        branches: 
            - master

jobs:
    build:
        name: Test PR
        runs-on: ubuntu-latest
        steps:        
            - name: Action Dockerfile
              run: echo $GITHUB_EVENT_NAME
