name: Test PR
on: 
    pull_request:
        types: [closed]

jobs:
    build:
        name: Hello world action
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
        
            - name: Action Dockerfile
              run: echo $GITHUB_EVENT_NAME
